


  - name: install the nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: import the roles
    ansible.builtin.import_role:
      name: common
      tasks_from: app-pre-req

  

  - name: copy the code
    ansible.builtin.template:
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify:
      - restarted nginx
